version: '3'

services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1338:1338"
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
    command: npm run develop
